In [8]:
import numpy as np
from fractions import Fraction

# Constructing the matrix A and vector s from the given transactions
A = np.array([[1, 1, 1],
              [3, 2, 1],
              [2, 1, 2]])

s = np.array([15, 28, 23])

# Displaying the components of A and s
A, s


(array([[1, 1, 1],
        [3, 2, 1],
        [2, 1, 2]]),
 array([15, 28, 23]))

In [9]:
# Constructing the matrix A and vector s from the given transactions
A = np.array([[1, 1, 1],
              [3, 2, 1],
              [2, 1, 2]])

s = np.array([15, 28, 23])

# Displaying the components of A and s
A, s


(array([[1, 1, 1],
        [3, 2, 1],
        [2, 1, 2]]),
 array([15, 28, 23]))

In [10]:
# Solving the system of equations using numpy's linear algebra solver
prices = np.linalg.solve(A, s)

# Convert the result to an array of fractions
prices_fraction = [Fraction(x).limit_denominator() for x in prices]

prices_fraction


[Fraction(3, 1), Fraction(7, 1), Fraction(5, 1)]